### PR TITLE
Don't read property of null

### PR DESCRIPTION
**Pull request by eivindfjeldstad**
When no session data is set, trying to get a value causes this exception:

```
TypeError: Cannot read property 'profile' of null
    at RedSess.<anonymous> (/Users/eivindfjeldstad/node/test/node_modules/redsess/redsess.js:101:14)
    at RedSess.<anonymous> (/Users/eivindfjeldstad/node/test/node_modules/redsess/redsess.js:112:12)
    at try_callback (/Users/eivindfjeldstad/node/test/node_modules/redis/index.js:484:9)
    at RedisClient.return_reply (/Users/eivindfjeldstad/node/test/node_modules/redis/index.js:555:13)
    at RedisReplyParser.<anonymous> (/Users/eivindfjeldstad/node/test/node_modules/redis/index.js:256:14)
    at RedisReplyParser.emit (events.js:87:17)
    at RedisReplyParser.send_reply (/Users/eivindfjeldstad/node/test/node_modules/redis/lib/parser/javascript.js:281:18)
    at RedisReplyParser.execute (/Users/eivindfjeldstad/node/test/node_modules/redis/lib/parser/javascript.js:166:26)
    at RedisClient.on_data (/Users/eivindfjeldstad/node/test/node_modules/redis/index.js:440:27)
    at Socket.<anonymous> (/Users/eivindfjeldstad/node/test/node_modules/redis/index.js:70:14)
```

### CODE REVIEW

**Comment by edpelesh** [comment]
+1 on this issue.

**Comment by gsf** [comment]
+1 patch works for me

**Comment by mnichols** [comment]
+1 for 'undefined' fix.

**Comment by isaacs** [comment]
Sorry, the `(all || {})[k]` was a bit too clever for my taste.  Fixed on abf9f679bb052b4d4131d4405d0386ad050322b0, published to npm on 0.0.8.

**Comment by mnichols** [comment]
HA! Thanks Isaac.
FYI when I try to `npm install` it  I am getting:

npm ERR! fetch failed
https://isaacs.iriscouch.com/registry/_design/app/_rewrite/redsess/-/redsess-0.0.8.tgz

Maybe I'm jumping the gun.

**Comment by isaacs** [comment]
Ah, whoops, I'm using an unconventional registry url, and there's a bug with doing that, apparently.  Fixed now.

**Pull request closed without merging**
