### PR TITLE
cookieOptions for passing options to cookies

### PR DESCRIPTION
**Pull request by robertjd**
`cookies` has get/set methods which take options, in our use case we need to pass `options.domain` to cookies.set

this patch exposes those options via redsess. another solution is to patch cookies and then pass this patched cookies instance to redsess:

https://github.com/jed/cookies/pull/17

### CODE REVIEW

**Comment by Raynos** [comment]
@isaacs added a test case for this.

**Comment by Raynos** [comment]
@isaacs ping

**Comment by isaacs** [comment]
This patch doesn't merge cleanly.  Can you rebase onto the latest master?

**Comment by isaacs** [comment]
Squashing to a single commit would be good, also.

**Comment by Raynos** [comment]
@isaacs It will merge cleanly.

I also tried to squash it but this happened instead >_<. git rebase ...

**Comment by Raynos** [comment]
@isaacs now it's one tidy commit

**Comment by isaacs** [comment]
Landed and publishing on 0.3.0.  Thanks!

**Pull request closed without merging**
