### PR TITLE
Add optional custom session token

### PR DESCRIPTION
**Pull request by twolfson**
This is a PR that allows for a custom session token. Currently, there is no way to use anything except for node's `crypto` module for generating a user's session token.

My use case is that during security evaluation, we felt more comfortable with using an already vetted source (e.g. `/dev/urandom`) for generating our random bytes.

### CODE REVIEW

**Comment by twolfson** [comment]
I have added tests to the PR. Sorry if the style isn't exactly what you want. I tried to keep it as consistent as possible.

**Comment by phated** [comment]
Makes sense to have this configurable.

**Comment by Raynos** [comment]
:+1:

**Comment by twolfson** [comment]
This PR has been open for 1 month. What has to be done to get this merged in?

**Comment by isaacs** [comment]
Thanks for the nudge.  Pushed on v0.4.0

**Comment by isaacs** [comment]
Just for what it's worth though, OpenSSL's random bytes API (ie, `require('crypto').randomBytes(n)`) is a cryptographically secure randomness, using machine entropy.  So, you're unlikely to get "better" data from `/dev/urandom`.  In fact, it's likely the exact same syscalls involved.

**Comment by twolfson** [comment]
Awesome, thanks! =)

**Pull request closed without merging**
